(function(){
  const TOOLTIP_CLASS="amtassist-tooltip",BADGE_CLASS="amtassist-badge",STORAGE_KEY="amtassist_lang";
  let currentLang="de";
  const FIELDS={steueridentifikationsnummer:{de:"Ihre 11-stellige Steuer-ID vom Finanzamt.",en:"Your 11-digit tax ID.",format:"XXXXXXXXXXX",required:true,regex:/steuer.?id|steuer.?identifikation/i},steuernummer:{de:"Ihre persönliche Steuernummer vom Finanzamt.",en:"Your personal tax number.",format:"XX/XXX/XXXXX",required:true,regex:/steuernummer/i},postleitzahl:{de:"Ihre 5-stellige Postleitzahl.",en:"5-digit postal code.",format:"XXXXX",required:true,regex:/postleitzahl|plz/i},geburtsdatum:{de:"Geburtsdatum im Format TT.MM.JJJJ.",en:"Date of birth DD.MM.YYYY.",format:"TT.MM.JJJJ",required:true,regex:/geburtsdatum|birth.?date/i},sozialversicherungsnummer:{de:"12-stellige SVNR auf Ihrer Versicherungskarte.",en:"12-digit social security number.",format:"12 Zeichen",required:false,regex:/sozialversicherung|svnr/i},aufenthaltstitel:{de:"Ihr aktueller Aufenthaltstitel.",en:"Your residence permit type.",format:"z.B. §18a",required:false,regex:/aufenthalts.?titel/i},bruttoeinkommen:{de:"Bruttogehalt vor Steuerabzügen.",en:"Gross salary before tax.",format:"EUR",required:false,regex:/brutto.?einkommen|brutto.?gehalt/i}};
  function findField(label){const n=label.trim().toLowerCase();for(const[k,d]of Object.entries(FIELDS)){if(d.regex.test(n))return{key:k,data:d};}return null;}
  function getLabelText(input){if(input.id){const l=document.querySelector('label[for="'+input.id+'"]');if(l)return l.textContent;}const p=input.closest("label");if(p)return p.textContent;return input.getAttribute("aria-label")||input.placeholder||"";}
  function injectStyles(){if(document.getElementById("aa-styles"))return;const s=document.createElement("style");s.id="aa-styles";s.textContent=`.${BADGE_CLASS}{display:inline-flex;align-items:center;justify-content:center;width:18px;height:18px;border-radius:50%;background:#1a56db;color:#fff;cursor:pointer;vertical-align:middle;flex-shrink:0;transition:background .15s}.${BADGE_CLASS}:hover{background:#1e429f}.${TOOLTIP_CLASS}{position:absolute;bottom:calc(100% + 8px);left:50%;transform:translateX(-50%);min-width:240px;max-width:320px;background:#1f2937;color:#f9fafb;border-radius:8px;padding:10px 12px;font-size:13px;line-height:1.5;pointer-events:none;opacity:0;transition:opacity .15s;z-index:999999}.${TOOLTIP_CLASS}.aa-visible{opacity:1}.aa-hdr{display:flex;gap:6px;align-items:center;margin-bottom:6px}.aa-fmt{font-family:monospace;font-size:11px;background:#374151;padding:1px 5px;border-radius:3px;color:#9ca3af}.aa-req{font-size:11px;background:#dc2626;color:#fff;padding:1px 6px;border-radius:3px;margin-left:auto}.aa-body{margin:0}`;document.head.appendChild(s);}
  function attachBadge(input,fieldData){if(input.dataset.aa)return;input.dataset.aa="1";const wrap=document.createElement("span");wrap.className=BADGE_CLASS;wrap.innerHTML='<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/></svg>';const tip=document.createElement("div");tip.className=TOOLTIP_CLASS;tip.innerHTML=`<div class="aa-hdr"><span class="aa-fmt">${fieldData.format||""}</span>${fieldData.required?'<span class="aa-req">Pflichtfeld</span>':""}</div><p class="aa-body">${fieldData[currentLang]||fieldData.de}</p>`;wrap.addEventListener("mouseenter",()=>tip.classList.add("aa-visible"));wrap.addEventListener("mouseleave",()=>tip.classList.remove("aa-visible"));const c=document.createElement("span");c.style.cssText="position:relative;display:inline-flex;align-items:center;margin-left:4px;";c.appendChild(wrap);c.appendChild(tip);if(input.nextSibling)input.parentNode.insertBefore(c,input.nextSibling);else input.parentNode.appendChild(c);}
  function scan(){injectStyles();const labeled=new Set();document.querySelectorAll("input,select,textarea").forEach(input=>{if(labeled.has(input))return;const t=getLabelText(input);if(!t)return;const m=findField(t);if(!m)return;labeled.add(input);attachBadge(input,m.data);});}
  new MutationObserver(muts=>{if(muts.some(m=>m.addedNodes.length>0))scan();}).observe(document.body,{childList:true,subtree:true});
  chrome.storage.local.get(STORAGE_KEY,r=>{currentLang=r[STORAGE_KEY]||"de";scan();});
  chrome.runtime.onMessage.addListener(msg=>{if(msg.type==="SET_LANG"){currentLang=msg.lang;}if(msg.type==="SCAN"||msg.type==="SET_LANG")scan();});
})();
